export const appConstants = {
    SELECT_DATE_RANGE: "SELECT_DATE_RANGE",
    TOTAL_NO_ROOM: "TOTAL_NO_ROOM",
    TOTAL_NO_GUEST: "TOTAL_NO_GUEST",
    SEARCH_CITY_NAME: "SEARCH_CITY_NAME",
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    ADD_TODO_FAILURE: "ADD_TODO_FAILURE",
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO_ITEM: "REMOVE_TODO_ITEM",
    TOGGLE_TODO_STATUS: "TOGGLE_TODO_STATUS"
};